
spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:ddddb;DB_CLOSE_ON_EXIT=TRUE;MODE=PostgreSQL
        sql-script-encoding: UTF-8
        username: sa
        password:
        initialization-mode: always
        schema: classpath:schema.sql
        data: classpath:data.sql

logging:
    level:
        '[org.springframework.web]': INFO
        '[omu.dddd.infrastructure]': DEBUG
    # file:
    #     name: logs/app.log